### ISSUE TITLE
upgrade

### ISSUE THREAD

**Issue by crazyants** [IdentityBaseNet/IdentityBase#10]
When do you finish the function?such as Authentication API,Multitenancy,Administration dashboard  etc.

**Comment by aruss** [comment]
- Administration dashboard is a separate project which is ongoing. 
- Multitenancy is planned but it will be a group of clients, a group will have default settings that can be shared accross of clients or each client will be configurable on its own. 
- Authentication API is currently supporting only invitation functions. 

I have currently a project that requeires all the stuff, so I would say it will be done all ASAP.
