### ISSUE TITLE
How can I start the migration?

### ISSUE THREAD

**Issue by Loongle** [IdentityBaseNet/IdentityBase#13]
sh dotnet ef migrations add init --context MigrationDbContext

then 

error message : Your startup project 'IdentityBase.EntityFramework.SqlServer' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again.

**Comment by iJzFan** [comment]
You can check the README.md under IdentityBase.EntityFramework.*Sql 

### Create migration files

```sh
dotnet ef migrations add init --context MigrationDbContext
```

**Comment by aruss** [comment]
Just create a empty database, setup your connection string then just start the application it will automatically migrate and seed the database. 

```json
 "EntityFramework": {
    "MigrateDatabase": true,
    "SeedExampleData": true,
    "EnableTokenCleanup": true,
    "SeedExampleDataPath": "./AppData",
    "SqlServer": {
      "ConnectionString": "Server=.\\SQLEXPRESS;Database=IdentityBase;User ID=dev;Password=dev"
    }
  }
 ...
  "Modules": [
    { "Type": "IdentityBase.EntityFramework.SqlServer.SqlServerModule, IdentityBase.EntityFramework.SqlServer" }
  }
```

**Comment by Loongle** [comment]
ok. been solved.
close.
