### ISSUE TITLE
Old ef Version referenced in IdentityBase.EntityFramework.IntegrationTests project

### ISSUE THREAD

**Issue by sassson** [IdentityBaseNet/IdentityBase#14]
in every project is used the version 2.0.2 of Microsoft.EntityFrameworkCore, except for the IdentityBase.EntityFramework.IntegrationTests, that is still used the 2.0.1 version.

https://github.com/IdentityBaseNet/IdentityBase/blob/develop/test/IdentityBase.EntityFramework.IntegrationTests/IdentityBase.EntityFramework.IntegrationTests.csproj

**Comment by aruss** [comment]
Fixed in 196bc3c64cf8fe52a11d26a5f74aa457489ae802
